export const typeContacts = `
export type IPerson = {
    id?: string;
    key?: string;
    firstName: string;
    lastName: string;
    firstNameLocal?: string;
    lastNameLocal?: string;
    shortDescription?: string;
    relations?: string;
    dateOfBirth?: string;
    imageUrl?: string;
    imageThumbUrl?: string;
    ratio?: number;
    socialTwitterUrl?: string;
    socialFacebookUrl?: string;
    socialInstagramUrl?: string;
    socialLinkedInUrl?: string;
    pinterestUrl?: string;
    wikipediaUrl?: string;
    website?: string;
    hometown?: string;
    city?: string;
    phoneNumber?: string;
    nationality?: string;
    email?: string;
    notes?: string;
    height?: number;
    netWorth?: number;
    company?: string;
    jobTitle?: string;
    tags: string[];
    dataTags: string[];
    tier?: number;
    gender?: string;
    category?: string;
};
    `;
